package za.co.eliteproject.strategy;

import za.co.eliteproject.model.LimitOrder;
import za.co.eliteproject.model.TradeRecord;

import java.util.List;
import java.util.PriorityQueue;

/**
 * Strategy pattern interface for order matching algorithms.
 */
public interface MatchingStrategy {

    /**
     * Matches orders in the given buy and sell queues, producing TradeRecords.
     *
     * @param buyQueue     priority queue of buy-side LimitOrders (best buy first)
     * @param sellQueue    priority queue of sell-side LimitOrders (best sell first)
     * @param tradeIdStart the trade ID to use for the first generated trade (incrementing thereafter)
     * @return the list of TradeRecords generated by matching
     */
    List<TradeRecord> match(PriorityQueue<LimitOrder> buyQueue,
                             PriorityQueue<LimitOrder> sellQueue,
                             int tradeIdStart);
}
